"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useCustomerAccount } from "@/components/customer-account-provider";
type Order = { id: string; trackingCode: string; status: string; createdAt: string; items: Array<{ name: string; description?: string; quantity: number }> };
export default function AccountOrdersPage() {
  const { token, ready, user } = useCustomerAccount(); const [orders, setOrders] = useState<Order[]>([]); const [error, setError] = useState("");
  useEffect(() => { if (!token) return; void fetch("/api/v1/customer-account/orders", { headers: { Authorization: `Bearer ${token}` } }).then(async r => { if (!r.ok) throw new Error("Не удалось загрузить заказы"); setOrders(await r.json()); }).catch(e => setError(e.message)); }, [token]);
  return <main className="mx-auto w-full max-w-[820px] flex-1 px-4 py-4 sm:px-6 sm:py-8"><h1 className="text-[30px] font-semibold tracking-tight sm:text-[34px]">Заказы</h1>{!ready ? <p className="mt-5 text-sm text-neutral-500">Загрузка…</p> : !user ? <p className="mt-5 text-sm text-neutral-600">Войдите в кабинет, чтобы увидеть заявки.</p> : error ? <p role="alert" className="mt-5 text-sm text-destructive">{error}</p> : orders.length ? <div className="mt-6 space-y-3">{orders.map(order => <article key={order.id} className="rounded-xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-2"><strong>Заявка № {order.trackingCode}</strong><span className="text-sm text-muted-foreground">{new Date(order.createdAt).toLocaleDateString("ru-RU")}</span></div><p className="mt-2 text-sm">Статус: {order.status}</p><ul className="mt-3 list-inside list-disc text-sm text-muted-foreground">{order.items.map((item,i) => <li key={`${item.name}-${i}`}>{item.name}{item.quantity > 1 ? ` × ${item.quantity}` : ""}</li>)}</ul></article>)}</div> : <div className="mt-6 py-8"><p className="font-medium text-[#222]">У вас пока нет заказов.</p><p className="mt-2 text-sm text-neutral-500">Когда вы оформите заявку, она появится здесь.</p><Link href="/" className="mt-5 inline-flex h-11 items-center rounded-lg bg-black px-5 text-sm font-medium text-white transition hover:bg-[#1a1a1a]">Перейти к товарам</Link></div>}</main>;
}
