"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useCustomerAccount } from "@/components/customer-account-provider";
type Profile = { email?: string; emailVerified: boolean; name?: string; phone?: string; contactTelegram?: string; whatsApp?: string; vk?: string; telegramLinked: boolean; notificationsEnabled: boolean; notificationsDisabledByAdmin: boolean };
type Address = { id: string; city?: string; street?: string; building?: string; apartment?: string; postalCode?: string; note?: string };
export default function AccountSettingsPage() {
  const { token, user, logout } = useCustomerAccount(); const [profile,setProfile]=useState<Profile|null>(null); const [addresses,setAddresses]=useState<Address[]>([]); const [notice,setNotice]=useState(""); const [error,setError]=useState(""); const [emailCodeSent,setEmailCodeSent]=useState(false);
  async function api<T>(path:string, init:RequestInit={}):Promise<T>{ const r=await fetch(`/api/v1/customer-account/${path}`,{...init,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json",...init.headers}}); if(!r.ok) {const e=await r.json().catch(()=>({})); throw new Error(e.message||e.title||"Не удалось сохранить изменения");} return r.status===204?undefined as T:await r.json() as T; }
  useEffect(()=>{ if(!token)return; void Promise.all([api<Profile>("profile"),api<Address[]>("addresses")]).then(([p,a])=>{setProfile(p);setAddresses(a)}).catch(e=>setError(e.message)); },[token]);
  async function saveProfile(event:React.FormEvent<HTMLFormElement>){event.preventDefault(); if(!profile)return; const form=new FormData(event.currentTarget); try{await api("profile",{method:"PUT",body:JSON.stringify({name:form.get("name"),phone:form.get("phone"),telegram:form.get("telegram"),whatsApp:form.get("whatsApp"),vk:form.get("vk")})}); setNotice("Контактные данные сохранены.");}catch(e){setError((e as Error).message)}}
  async function toggleNotifications(){if(!profile)return;try{await api("notifications",{method:"PUT",body:JSON.stringify({enabled:!profile.notificationsEnabled})});setProfile({...profile,notificationsEnabled:!profile.notificationsEnabled});}catch(e){setError((e as Error).message)}}
  async function linkTelegram(){try{const d=await api<{authorizationUrl:string}>("telegram/link/start",{method:"POST",body:"{}"});sessionStorage.setItem("customerTelegramLink","1");window.location.assign(d.authorizationUrl);}catch(e){setError((e as Error).message)}}
  async function unlinkTelegram(){try{await api("telegram",{method:"DELETE"});setProfile(profile?{...profile,telegramLinked:false,notificationsEnabled:false}:null);}catch(e){setError((e as Error).message)}}
  async function addAddress(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);try{const a=await api<Address>("addresses",{method:"POST",body:JSON.stringify({city:form.get("city"),street:form.get("street"),building:form.get("building"),apartment:form.get("apartment"),postalCode:form.get("postalCode"),note:form.get("note")})});setAddresses([a,...addresses]);event.currentTarget.reset();setNotice("Адрес добавлен.");}catch(e){setError((e as Error).message)}}
  async function deleteAddress(id:string){try{await api(`addresses/${id}`,{method:"DELETE"});setAddresses(addresses.filter(a=>a.id!==id));}catch(e){setError((e as Error).message)}}
  async function changeEmail(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const email=String(form.get("email")||"");try{if(!emailCodeSent){await api("email/change/send-code",{method:"POST",body:JSON.stringify({email})});setEmailCodeSent(true);setNotice("Код подтверждения отправлен на новый email.");}else{await api("email/change/verify-code",{method:"POST",body:JSON.stringify({email,code:form.get("code")})});setEmailCodeSent(false);setProfile(profile?{...profile,email,emailVerified:true}:null);setNotice("Email изменён.");}}catch(e){setError((e as Error).message)}}
  async function changePassword(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);try{await fetch("/api/v1/auth/change-password",{method:"PUT",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({currentPassword:f.get("currentPassword"),newPassword:f.get("newPassword")})}).then(async r=>{if(!r.ok){const x=await r.json().catch(()=>({}));throw new Error(x.detail||x.title||"Не удалось изменить пароль")}});await logout();window.location.assign("/login");}catch(e){setError((e as Error).message)}}
  if(!user)return <main className="mx-auto flex-1 px-4 py-12 text-center">Сначала <Link className="underline" href="/login">войдите в кабинет</Link>.</main>;
  return <main className="mx-auto w-full max-w-3xl flex-1 px-4 py-10"><h1 className="text-3xl font-semibold">Настройки</h1>{notice?<p className="mt-4 text-sm text-emerald-700">{notice}</p>:null}{error?<p role="alert" className="mt-4 text-sm text-destructive">{error}</p>:null}
  {profile?<><form onSubmit={saveProfile} className="mt-6 space-y-4 rounded-xl border p-5"><h2 className="text-lg font-semibold">Контактные данные</h2><p className="text-sm text-muted-foreground">Email: {profile.email||user.login} {profile.emailVerified?"(подтверждён)":""}</p>{([['name','Имя',profile.name],['phone','Телефон',profile.phone],['telegram','Telegram для связи',profile.contactTelegram],['whatsApp','WhatsApp',profile.whatsApp],['vk','VK',profile.vk]] as const).map(([name,label,value])=><label key={name} className="block text-sm">{label}<input name={name} defaultValue={value||""} className="mt-1 h-10 w-full rounded-lg border px-3"/></label>)}<button className="rounded-lg bg-black px-4 py-2 text-white">Сохранить</button></form>
  <form onSubmit={changeEmail} className="mt-4 space-y-3 rounded-xl border p-5"><h2 className="text-lg font-semibold">Изменить email</h2><input name="email" type="email" required placeholder="Новый email" className="h-10 w-full rounded-lg border px-3"/>{emailCodeSent?<input name="code" required inputMode="numeric" maxLength={6} placeholder="Код из письма" className="h-10 w-full rounded-lg border px-3"/>:null}<button className="rounded-lg border px-4 py-2 text-sm">{emailCodeSent?"Подтвердить новый email":"Отправить код"}</button></form>
  <form onSubmit={changePassword} className="mt-4 space-y-3 rounded-xl border p-5"><h2 className="text-lg font-semibold">Сменить пароль</h2><input name="currentPassword" type="password" required placeholder="Текущий пароль" className="h-10 w-full rounded-lg border px-3"/><input name="newPassword" type="password" minLength={8} required placeholder="Новый пароль (от 8 символов)" className="h-10 w-full rounded-lg border px-3"/><button className="rounded-lg border px-4 py-2 text-sm">Изменить пароль</button></form>
  <section className="mt-4 rounded-xl border p-5"><h2 className="text-lg font-semibold">Telegram и уведомления</h2><p className="mt-1 text-sm text-muted-foreground">Уведомление о создании заявки придёт в привязанный Telegram.</p><div className="mt-4 flex flex-wrap items-center gap-3">{profile.telegramLinked?<><span className="text-sm">Telegram привязан</span><button onClick={()=>void unlinkTelegram()} className="rounded-lg border px-3 py-2 text-sm">Отвязать</button></>:<button onClick={()=>void linkTelegram()} className="rounded-lg bg-[#229ED9] px-4 py-2 text-white">Привязать Telegram</button>}</div>{profile.telegramLinked?<label className="mt-4 flex items-center gap-3 text-sm"><input type="checkbox" checked={profile.notificationsEnabled} disabled={profile.notificationsDisabledByAdmin} onChange={()=>void toggleNotifications()}/>Получать уведомления{profile.notificationsDisabledByAdmin?" (временно отключены поддержкой)":""}</label>:null}</section>
  <section className="mt-4 rounded-xl border p-5"><h2 className="text-lg font-semibold">Адреса</h2><div className="mt-3 space-y-2">{addresses.map(a=><div key={a.id} className="flex justify-between gap-3 rounded-lg bg-muted/40 p-3 text-sm"><span>{[a.city,a.street,a.building,a.apartment].filter(Boolean).join(", ")}</span><button onClick={()=>void deleteAddress(a.id)} className="text-destructive">Удалить</button></div>)}</div><form onSubmit={addAddress} className="mt-4 grid gap-2 sm:grid-cols-2">{[['city','Город'],['street','Улица'],['building','Дом'],['apartment','Квартира'],['postalCode','Индекс'],['note','Комментарий']].map(([n,l])=><input key={n} name={n} placeholder={l} className="h-10 rounded-lg border px-3 text-sm"/>)}<button className="rounded-lg border px-4 py-2 text-sm sm:col-span-2">Добавить адрес</button></form></section></>:<p className="mt-6">Загрузка настроек…</p>}</main>;
}
